services:
  alertnav:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - alertnav-network

networks:
  alertnav-network:
    driver: bridge
